// Restaurant data with full menus
export const restaurants = [
  {
    id: 1,
    name: "Spice Garden",
    cuisine: "North Indian, Mughlai",
    category: ["Biryani", "North Indian"],
    rating: 4.5,
    reviews: 2341,
    delivery: 28,
    cost: 350,
    veg: false,
    badge: "Bestseller",
    discount: "20% off above ₹299",
    emoji: "🍛",
    bg: "linear-gradient(135deg,#ffecd2,#fcb69f)",
    menu: {
      Starters: [
        { id: "s1_1", name: "Chicken Tikka", price: 299, desc: "Marinated chicken grilled in tandoor", veg: false },
        { id: "s1_2", name: "Paneer Tikka", price: 249, desc: "Spiced cottage cheese grilled to perfection", veg: true },
        { id: "s1_3", name: "Seekh Kebab", price: 279, desc: "Minced mutton kebabs on skewers", veg: false },
      ],
      "Main Course": [
        { id: "s1_4", name: "Butter Chicken", price: 349, desc: "Creamy tomato-based chicken curry", veg: false },
        { id: "s1_5", name: "Dal Makhani", price: 249, desc: "Slow-cooked black lentils with butter", veg: true },
        { id: "s1_6", name: "Paneer Butter Masala", price: 299, desc: "Rich cottage cheese in buttery gravy", veg: true },
      ],
      Biryani: [
        { id: "s1_7", name: "Chicken Dum Biryani", price: 399, desc: "Slow-cooked fragrant rice with chicken", veg: false },
        { id: "s1_8", name: "Veg Biryani", price: 299, desc: "Aromatic basmati rice with vegetables", veg: true },
      ],
      Breads: [
        { id: "s1_9", name: "Butter Naan", price: 49, desc: "Soft leavened bread baked in tandoor", veg: true },
        { id: "s1_10", name: "Laccha Paratha", price: 59, desc: "Layered whole wheat flatbread", veg: true },
      ],
    },
  },
  {
    id: 2,
    name: "Pizza Paradise",
    cuisine: "Italian, Pizza, Pasta",
    category: ["Pizza"],
    rating: 4.3,
    reviews: 1892,
    delivery: 25,
    cost: 500,
    veg: false,
    badge: "Popular",
    discount: "Buy 1 Get 1 Free",
    emoji: "🍕",
    bg: "linear-gradient(135deg,#a1c4fd,#c2e9fb)",
    menu: {
      "Classic Pizzas": [
        { id: "s2_1", name: "Margherita", price: 299, desc: "Classic tomato sauce with mozzarella", veg: true },
        { id: "s2_2", name: "Farmhouse", price: 359, desc: "Loaded with capsicum, onion & mushroom", veg: true },
        { id: "s2_3", name: "Chicken BBQ", price: 429, desc: "Smoky BBQ sauce with grilled chicken", veg: false },
        { id: "s2_4", name: "Pepperoni Feast", price: 469, desc: "Double pepperoni with extra cheese", veg: false },
      ],
      Pasta: [
        { id: "s2_5", name: "Penne Arrabbiata", price: 249, desc: "Spicy tomato pasta with herbs", veg: true },
        { id: "s2_6", name: "Chicken Alfredo", price: 329, desc: "Creamy white sauce pasta with chicken", veg: false },
      ],
      "Sides & Drinks": [
        { id: "s2_7", name: "Garlic Bread", price: 149, desc: "Toasted bread with garlic butter", veg: true },
        { id: "s2_8", name: "Coke (500ml)", price: 79, desc: "Chilled Coca-Cola", veg: true },
      ],
    },
  },
  {
    id: 3,
    name: "Burger Barn",
    cuisine: "Burgers, American, Wraps",
    category: ["Burger"],
    rating: 4.1,
    reviews: 987,
    delivery: 20,
    cost: 300,
    veg: false,
    badge: null,
    discount: "15% off on first order",
    emoji: "🍔",
    bg: "linear-gradient(135deg,#d4fc79,#96e6a1)",
    menu: {
      "Signature Burgers": [
        { id: "s3_1", name: "Classic Beef Burger", price: 259, desc: "Juicy beef patty with lettuce & tomato", veg: false },
        { id: "s3_2", name: "Crispy Chicken Burger", price: 229, desc: "Fried chicken with coleslaw & pickles", veg: false },
        { id: "s3_3", name: "Veggie Delight", price: 199, desc: "Spiced veggie patty with fresh veggies", veg: true },
        { id: "s3_4", name: "Double Smash Burger", price: 349, desc: "Double smashed patties with special sauce", veg: false },
      ],
      Sides: [
        { id: "s3_5", name: "Loaded Fries", price: 169, desc: "Cheese sauce, jalapeños & crispy onion", veg: true },
        { id: "s3_6", name: "Onion Rings", price: 129, desc: "Beer-battered crispy onion rings", veg: true },
      ],
      Beverages: [
        { id: "s3_7", name: "Chocolate Shake", price: 149, desc: "Thick creamy chocolate milkshake", veg: true },
        { id: "s3_8", name: "Fresh Lime Soda", price: 89, desc: "Refreshing lime with sparkling water", veg: true },
      ],
    },
  },
  {
    id: 4,
    name: "Wok & Roll",
    cuisine: "Chinese, Pan-Asian, Thai",
    category: ["Chinese"],
    rating: 4.4,
    reviews: 1543,
    delivery: 35,
    cost: 400,
    veg: false,
    badge: "Trending",
    discount: null,
    emoji: "🥡",
    bg: "linear-gradient(135deg,#fbc2eb,#a6c1ee)",
    menu: {
      Starters: [
        { id: "s4_1", name: "Spring Rolls (6 pcs)", price: 189, desc: "Crispy rolls with vegetable filling", veg: true },
        { id: "s4_2", name: "Chicken Dim Sum", price: 229, desc: "Steamed dumplings with soy dip", veg: false },
        { id: "s4_3", name: "Manchurian Balls", price: 199, desc: "Fried balls in spicy manchurian sauce", veg: true },
      ],
      "Rice & Noodles": [
        { id: "s4_4", name: "Chicken Fried Rice", price: 249, desc: "Wok-tossed rice with egg & chicken", veg: false },
        { id: "s4_5", name: "Veg Hakka Noodles", price: 209, desc: "Stir-fried noodles with fresh veggies", veg: true },
        { id: "s4_6", name: "Pad Thai", price: 279, desc: "Thai-style noodles with peanuts & lime", veg: false },
      ],
      Mains: [
        { id: "s4_7", name: "Kung Pao Chicken", price: 319, desc: "Spicy stir-fry with peanuts & chilli", veg: false },
        { id: "s4_8", name: "Tofu in Black Bean", price: 269, desc: "Silken tofu in savory black bean sauce", veg: true },
      ],
    },
  },
  {
    id: 5,
    name: "Dosa Diner",
    cuisine: "South Indian, Tamil Nadu, Kerala",
    category: ["South Indian"],
    rating: 4.6,
    reviews: 3102,
    delivery: 22,
    cost: 200,
    veg: true,
    badge: "Pure Veg",
    discount: "Free Sambar with every order",
    emoji: "🥘",
    bg: "linear-gradient(135deg,#f6d365,#fda085)",
    menu: {
      Dosas: [
        { id: "s5_1", name: "Masala Dosa", price: 129, desc: "Crispy dosa with spiced potato filling", veg: true },
        { id: "s5_2", name: "Onion Rava Dosa", price: 149, desc: "Crispy rava dosa with onion & jeera", veg: true },
        { id: "s5_3", name: "Ghee Roast Dosa", price: 169, desc: "Golden dosa smeared with pure ghee", veg: true },
        { id: "s5_4", name: "Set Dosa (3 pcs)", price: 119, desc: "Soft spongy dosas served with chutneys", veg: true },
      ],
      "Idli & Vada": [
        { id: "s5_5", name: "Idli (4 pcs)", price: 89, desc: "Steamed rice cakes with sambar & chutney", veg: true },
        { id: "s5_6", name: "Medu Vada (2 pcs)", price: 99, desc: "Crispy lentil donuts with sambar", veg: true },
      ],
      "Rice Meals": [
        { id: "s5_7", name: "South Indian Thali", price: 199, desc: "Full meal with rice, sambar, rasam & more", veg: true },
        { id: "s5_8", name: "Curd Rice", price: 99, desc: "Cooling yogurt rice with tempering", veg: true },
      ],
    },
  },
  {
    id: 6,
    name: "Sweet Tooth",
    cuisine: "Desserts, Ice Cream, Cake",
    category: ["Desserts"],
    rating: 4.7,
    reviews: 2765,
    delivery: 40,
    cost: 250,
    veg: true,
    badge: "Top Rated",
    discount: "Free dessert on orders above ₹500",
    emoji: "🍨",
    bg: "linear-gradient(135deg,#84fab0,#8fd3f4)",
    menu: {
      "Ice Cream": [
        { id: "s6_1", name: "Belgian Choco Tub", price: 399, desc: "Premium Belgian chocolate ice cream 500ml", veg: true },
        { id: "s6_2", name: "Sundae Special", price: 199, desc: "3 scoops with hot fudge & nuts", veg: true },
        { id: "s6_3", name: "Kulfi Sticks (4 pcs)", price: 149, desc: "Traditional Indian frozen dessert", veg: true },
      ],
      "Cakes & Pastries": [
        { id: "s6_4", name: "Tiramisu", price: 259, desc: "Classic Italian coffee dessert", veg: true },
        { id: "s6_5", name: "Gulab Jamun (6 pcs)", price: 149, desc: "Soft milk solid dumplings in sugar syrup", veg: true },
        { id: "s6_6", name: "Cheesecake Slice", price: 199, desc: "New York style baked cheesecake", veg: true },
      ],
      "Waffles & Crepes": [
        { id: "s6_7", name: "Nutella Waffle", price: 219, desc: "Crispy waffle with Nutella & banana", veg: true },
        { id: "s6_8", name: "Strawberry Crepe", price: 179, desc: "Thin crepe with strawberry compote & cream", veg: true },
      ],
    },
  },
  {
    id: 7,
    name: "Biryani House",
    cuisine: "Biryani, Mughlai, Kebabs",
    category: ["Biryani"],
    rating: 4.8,
    reviews: 4211,
    delivery: 45,
    cost: 500,
    veg: false,
    badge: "#1 Biryani",
    discount: "10% off on all orders",
    emoji: "🍚",
    bg: "linear-gradient(135deg,#a18cd1,#fbc2eb)",
    menu: {
      Biryani: [
        { id: "s7_1", name: "Hyderabadi Dum Biryani", price: 449, desc: "Authentic slow-cooked biryani with saffron", veg: false },
        { id: "s7_2", name: "Lucknowi Biryani", price: 429, desc: "Subtle spiced biryani with tender meat", veg: false },
        { id: "s7_3", name: "Veg Dum Biryani", price: 349, desc: "Fragrant rice with mixed vegetables", veg: true },
        { id: "s7_4", name: "Egg Biryani", price: 369, desc: "Biryani with spiced boiled eggs", veg: false },
      ],
      Sides: [
        { id: "s7_5", name: "Raita", price: 79, desc: "Cooling yogurt with cucumber & spices", veg: true },
        { id: "s7_6", name: "Mirchi Ka Salan", price: 99, desc: "Spiced green chilli curry", veg: true },
      ],
    },
  },
  {
    id: 8,
    name: "Green Bowl",
    cuisine: "Healthy, Salads, Juices",
    category: ["Healthy"],
    rating: 4.2,
    reviews: 876,
    delivery: 30,
    cost: 450,
    veg: true,
    badge: "Healthy",
    discount: null,
    emoji: "🥗",
    bg: "linear-gradient(135deg,#fccb90,#d57eeb)",
    menu: {
      Salads: [
        { id: "s8_1", name: "Caesar Salad", price: 299, desc: "Romaine, croutons, parmesan & caesar dressing", veg: true },
        { id: "s8_2", name: "Greek Salad", price: 279, desc: "Fresh veggies with feta & olives", veg: true },
        { id: "s8_3", name: "Quinoa Power Bowl", price: 349, desc: "Quinoa with roasted veggies & tahini", veg: true },
      ],
      "Smoothies & Juices": [
        { id: "s8_4", name: "Green Detox", price: 199, desc: "Spinach, cucumber, ginger & lemon", veg: true },
        { id: "s8_5", name: "Berry Blast", price: 229, desc: "Mixed berries with almond milk", veg: true },
        { id: "s8_6", name: "Mango Lassi", price: 159, desc: "Fresh mango with chilled yogurt", veg: true },
      ],
      Wraps: [
        { id: "s8_7", name: "Hummus Veggie Wrap", price: 249, desc: "Whole wheat wrap with hummus & grilled veggies", veg: true },
        { id: "s8_8", name: "Falafel Wrap", price: 229, desc: "Crispy falafel with tzatziki", veg: true },
      ],
    },
  },
];

// FAQ accordion data (fixed encoding)
export const questions = [
  {
    id: 1,
    title: "Popular cuisines near me",
    infos: [
      "Bakery food near me • ",
      "Beverages food near me • ",
      "Biryani food near me • ",
      "Burger food near me • ",
      "Chinese food near me • ",
      "Desserts food near me • ",
      "Ice Cream food near me • ",
      "North Indian food near me • ",
      "Pizza food near me • ",
      "South Indian food near me • ",
      "Street food near me • ",
    ],
  },
  {
    id: 2,
    title: "Popular restaurant types near me",
    infos: [
      "Cafés near me • ",
      "Casual Dining near me • ",
      "Dessert Parlors near me • ",
      "Fine Dining near me • ",
      "Food Trucks near me • ",
      "Quick Bites near me • ",
      "Sweet Shops near me • ",
    ],
  },
  {
    id: 3,
    title: "Top Restaurant Chains",
    infos: [
      "KFC • ",
      "Paradise Biryani • ",
      "Pizza Hut • ",
      "Wow Momo • ",
      "Dominos • ",
    ],
  },
];

export default questions;
